import {Page} from "./stores";

export const PageName = new Map([
	[Page.UNKNOWN, "Unknown"],
	[Page.DOWNLOAD, "Download Resources"],
	[Page.DESIGNS, "My Gallifreyan Designs"],
	[Page.SCG, "Sherman's Circular Gallifreyan Guide"],
	[Page.ABOUT_ME, "About Me"],
	[Page.CONTACT, "Contact Me"],
	[Page.HOME, "Gallifreyan Guides Overview"],
	[Page.CHANGELOG, "gallifreyan.info Changelog"],
	[Page.IMPRINT, "Imprint"],
	[Page.PRIVACY, "Privacy Policy"]
]);

export const guidePages = [Page.SCG];

export const LANGUAGE = {
	SCG: 1
}

export const LANGUAGE_NAME_MAP = new Map([
	[LANGUAGE.SCG, "Sherman's Circular Gallifreyan"]
]);

export const DOCTOR_WHO_KEYWORDS = [
	"gallifreyan",
	"galifreyan",
	"gallyfreyan",
	"galyfreyan",
	"gallifreian",
	"galifreian",
	"gallifrean",
	"galifrean",
	"gallyfrean",
	"galiyfrean",
	"doctor who",
	"doctor",
	"who",
	"tardis",
	"timey wimey",
	"timey-wimey",
	"companion",
	"rosa",
	"souffle girl",
	"steve moffat",
	"time lord",
	"gallifrey",
	"galifrey",
	"gallifrei",
	"galifrei",
	"gallimaufry",
	"exterminate",
	"cybermen",
	"cyberman",
	"sontaran",
	"sonic",
	"screwdriver",
	"sonic screwdriver",
	"torchwood",
	"behind the sofa",
	"whovian",
	"first doctor",
	"second doctor",
	"third doctor",
	"fourth doctor",
	"fifth doctor",
	"sixth doctor",
	"seventh doctor",
	"eighth doctor",
	"war doctor",
	"ninth doctor",
	"tenth doctor",
	"eleventh doctor",
	"twelfth doctor",
	"thirteenth doctor",
	"jodie whittaker",
	"peter capaldi",
	"matt smith",
	"david tennant",
	"christopher eccleston",
	"john hurt",
	"paul mcgann",
	"sylvester mccoy",
	"colin baker",
	"peter davison",
	"tom baker",
	"jon pertwee",
	"patrick troughton",
	"william hartnell",
	"time travel",
	"time vortex",
	"how to",
	"how",
	"guide",
	"explain",
	"explanation",
	"language",
	"conlang",
	"write",
	"script",
	"script",
	"sentences",
	"words",
	"numbers",
	"alphabet",
];